name: C/C++ CI

on:
  push:
    branches: [ "main", "cicd" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_linux:
  
    runs-on: ubuntu-latest       

    steps:
    - uses: actions/checkout@v4
    - name: compile
      run: cd src && gcc -o wav2tzx wav2tzx.c

  build_win_x64_mingw:
  
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up MinGW
      uses: e-t-l/setup-mingw@patch-1
      with:
        platform: x64
    - name: compile
      run: cd src && gcc -o wav2tzx wav2tzx.c

  build_macos_universal:
  
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v4
    - name: compile
      run: cd src && gcc -arch arm64 -arch x86_64 -x c -o wav2tzx wav2tzx.c
